@apiUrl = http://127.0.0.1:8080

### Get all rooms
GET {{apiUrl}}/rooms

###
GET {{apiUrl}}/bookings

### Create a new booking
POST {{apiUrl}}/bookings
Content-Type: application/json

{
    "room_id": 1
}